import { Logic } from "../logic.slint";

export component RandPoint inherits Rectangle {
    // Look

    in property <length> size: 20px;
    background: Logic.group_color(self.model_rel_group);
    width: self.size;
    height: self.size;

    // Model

    /// Group number.
    in-out property <int> model_group;
    in property <float> model_rel_group;
    out property <float> model_x: Logic.rand_fract_float();
    out property <float> model_y: Logic.rand_fract_float();
}
