import { GroupableSprite } from "groupable.slint";
import { Logic } from "../logic.slint";

export component Centroid inherits GroupableSprite {
    // Model – Implemented
    model_x: clamp(Logic.rand_fract_float(), 0.3, 0.7);
    model_y: clamp(Logic.rand_fract_float(), 0.3, 0.7);

    // Look – Provided
    in property <float> alpha: 0.5;
    // Look – Overridden
    background: Logic.group_color_with_alpha(self.model_rel_group, self.alpha);
    scale: 60;
}
