export global GuiCfg {
    // Font
    in-out property <length> font_size: 50px;
    // Widget ratios
    in-out property <float> point_to_centroid_s_mult: 4;
    // Point scale
    in-out property <float> min_point_scale: 5;
    in-out property <float> default_point_scale: 20;
    in-out property <float> max_point_scale: 80;
}

export global AppCfg{
    // Group count
    in-out property <int> min_group_count: 2;
    in-out property <int> default_group_count: 3;
    in-out property <int> max_group_count: 10;
    // Point count
    in-out property <int> min_point_count: 5;
    in-out property <int> default_point_count: 100;
    in-out property <int> max_point_count; // Set from $proj_root/src/lib.rs
    // Simulation step
    in-out property <int> min_simul_step: 0;
    in-out property <int> default_simul_step: 0;
    in-out property <int> max_simul_step: 255;
}
