export global GuiCfg {
    in-out property <length> font_size: 50px;
}

export global AppCfg{
    // Group count
    in-out property <int> min_group_count: 2;
    in-out property <int> default_group_count: 3;
    in-out property <int> max_group_count: 10;
    // Point count
    in-out property <int> min_point_count: 5;
    in-out property <int> default_point_count: 100;
    in-out property <int> max_point_count: 999;
    // Point size
    in-out property <int> min_point_size: 5;
    in-out property <int> default_point_size: 20;
    in-out property <int> max_point_size: 80;
}
