export global Logic {
    pure callback rand_fract_float() -> float;
    pure callback rand_natural_int() -> int;
    pure callback point_x(int) -> float;
    pure callback point_y(int) -> float;
    pure callback group_color(float) -> color;
    pure callback group_color_with_alpha(float, float) -> color;
    pure callback loosely_parse_int(string) -> int;
    callback algorithm_step(string);
} 

