import { Button, HorizontalBox } from "std-widgets.slint";
import { Logic } from "../../logic.slint";
import { StepCountInput } from "../step_input.slint";
import { GuiCfg } from "../../cfg.slint";

component SubseqStepButt inherits TouchArea {
    Image {
        source: @image-url("./navigation_e.svg");
        height: GuiCfg.font_size * 125%;
    }
}

export component SubseqStepBox inherits Rectangle {
    border-width: GuiCfg.font_size * 2%;
    border-color: black;

    in-out property <int> current_step;
    in-out property <string> steps_in_batch;

    HorizontalBox {
        StepCountInput {
            steps_in_batch <=> root.steps_in_batch;
        }

        SubseqStepButt {
            clicked => {
                root.current_step += Logic.loosely_parse_int(root.steps_in_batch);
            }
        }
    }
}
