import { Button, HorizontalBox } from "std-widgets.slint";
import { Logic } from "../../logic.slint";
import { StepCountInput } from "../step_input.slint";
import { GuiCfg } from "../../cfg.slint";

component SubseqStepButt inherits TouchArea {
    Image {
        source: @image-url("./navigation_e.svg");
        height: GuiCfg.font_size * 125%;
    }
}

export component SubseqStepBox inherits Rectangle {
    border-width: GuiCfg.font_size * 2%;
    border-color: black;

    in-out property <string> step_count;

    HorizontalBox {
        StepCountInput {
            step_count <=> root.step_count;
        }

        SubseqStepButt {
            clicked => {
                Logic.algorithm_step(root.step_count)
            }
        }
    }
}
