import { GuiCfg } from "../cfg.slint";

export component StepCountInput inherits TextInput {
    in-out property <string> steps_in_batch;

    // Input properties
    text <=> root.steps_in_batch;
    input-type: InputType.number;
    // Display properties
    font-size: GuiCfg.font_size;
    vertical-alignment: TextVerticalAlignment.center;
    horizontal-alignment: TextHorizontalAlignment.center;
}
