import { Logic } from "../logic.slint";
import { RandPoint } from "../point/rand.slint";
import { AppCfg, GuiCfg } from "../cfg.slint";
import { Centroid } from "../point/centroid.slint";

export component MainPlane inherits Rectangle {
    in property <int> group_count;
    in property <int> point_count;
    in property <float> point_size: AppCfg.default_point_size;

    for group_num in self.group_count: Centroid {
        // Model
        model_group: group_num;
        model_rel_group: self.model_group / root.group_count;
        // Look
        size: GuiCfg.point_to_centroid_s_mult * 0.01px * root.point_size * sqrt(parent.width * parent.height / root.point_count / (1px * 1px));
        // Visual location
        x: self.model_x * (parent.width - self.width / GuiCfg.point_to_centroid_s_mult);
        y: 0.92 * self.model_y * (parent.height - self.height / GuiCfg.point_to_centroid_s_mult);
    }

    for idx in self.point_count: RandPoint {
        // Model
        model_group: mod(Logic.rand_natural_int(), group_count);
        model_rel_group: self.model_group / root.group_count;
        // Look
        size: sqrt(parent.width * parent.height / root.point_count / (1px * 1px)) * root.point_size * 0.01px;
        // Visual location
        x: self.model_x * (parent.width - self.width);
        y: 0.92 * self.model_y * (parent.height - self.height);
    }
}
