import { MainToolbar } from "../main/toolbar.slint";
import { VerticalBox } from "std-widgets.slint";
import { MainPlane } from "./plane.slint";
import { GuiCfg } from "../cfg.slint";
import { Logic } from "../logic.slint";
import { GuiCfg, AppCfg } from "../cfg.slint";

export component MainFrame inherits VerticalBox {
    toolbar := MainToolbar {
        height: 10%;
    }

    main_plain := MainPlane {
        // Provided model
        group_count: clamp(Logic.loosely_parse_int(toolbar.group_count), AppCfg.min_group_count, AppCfg.max_group_count);
        point_count: clamp(Logic.loosely_parse_int(toolbar.point_count), AppCfg.min_point_count, AppCfg.max_point_count);
        simul_step: toolbar.current_step;
        // Provided – Look
        height: 90%;
        point_scale: clamp(Logic.loosely_parse_int(toolbar.point_scale), GuiCfg.min_point_scale, GuiCfg.max_point_scale);
    }
}

export component MainWindow inherits Window {
    min-width: 1400px;
    min-height: (self.min-width / 2) + GuiCfg.font_size;
    MainFrame { }
}
